---
- name: Deploying frontend with Kubernetes
  hosts: localhost
  remote_user: dhamodhar
  tasks:
    - name: create frontend deployment
      kubernetes.core.k8s:
        definition: "{{ lookup('file', './deploy-frontend.yaml') | from_yaml }}"
        state: present
    - name: create frontend service
      kubernetes.core.k8s:
        definition: "{{ lookup('file', './service-frontend.yaml') | from_yaml }}" 
        state: present
